- name: map-checkout
  hosts: "{{Environment}}"
  vars_prompt:
    name: application
    prompt: Enter application name

  tasks:

    - name: SOE
      shell: sh *hidden*
      when: "'soe' in application"
      register: SOE

    - name: Write results to SOE logfile
      blockinfile:
        create: yes
        path: "*hidden*"
        mode: 0777
        backup: yes
        insertafter: BOF
        block: "{{ SOE.stdout }}"
        marker: "# {{ inventory_hostname }} {mark}"
      when: "'soe' in application"
      delegate_to: localhost


    - name: SMA
      shell: sh *hidden*
      when: "'sma' in application"
      register: SMA

    - name: Write results to SMA logfile
      blockinfile:
        create: yes
        path: "*hidden*"
        mode: 0777
        backup: yes
        insertafter: BOF
        block: "{{ SMA.stdout }}"
        marker: "# {{ inventory_hostname }} {mark}"
      when: "'sma' in application"
      delegate_to: localhost

    - name: MAC
      shell: sh *hidden*
      when: "'mac' in application"
      register: MAC
    
    - name: Write results to MAC logfile
      blockinfile:
        create: yes
        path: "*hidden*"
        mode: 0777
        backup: yes
        insertafter: BOF
        block: "{{ MAC.stdout }}"
        marker: "# {{ inventory_hostname }} {mark}"
      when: "'mac' in application"
      delegate_to: localhost


    - name: DAP
      shell: sh *hidden*
      when: "'dap' in application"
      register: DAP

    - name: Write results to DAP logfile
      blockinfile:
        create: yes
        path: "*hidden*"
        mode: 0777
        backup: yes
        insertafter: BOF
        block: "{{ DAP.stdout }}"
        marker: "# {{ inventory_hostname }} {mark}"
      when: "'dap' in application"
      delegate_to: localhost

    - name: CGW
      shell: sh *hidden*
      when: "'cgw' in application"
      register: CGW

    - name: Write results to CGW logfile
      blockinfile:
        create: yes
        path: "*hidden*"
        mode: 0777
        backup: yes
        insertafter: BOF
        block: "{{ CGW.stdout }}"
        marker: "# {{ inventory_hostname }} {mark}"
      when: "'cgw' in application"
      delegate_to: localhost

    - name: Write results to GUI logfile
      blockinfile:
        create: yes
        path: "*hidden*"
        mode: 0777
        backup: yes
        insertafter: BOF
        block: "{{ GUI.stdout }}"
        marker: "# {{ inventory_hostname }} {mark}"
      when: "'gui' in application"
      delegate_to: localhost
      
      #paths are *hidden* due to security reasons
