---

- name : modify the content of the hosts file
  hosts : all
  tasks :
   - name : copy the content from myhosts.j2 to /etc/hosts
     template : src=myhosts.j2 dest=/etc/hosts
     when : inventory_hostname in groups['dev']
