- name: master - playbook
  hosts: test_servers
  vars_prompt:
    - name: var
      prompt: " Enter the corresponding numeric notation , for the required task (1)start/(2)stop/(3)restart"
      private: no
  tasks:
    - debug: 
        var: "var"
      register: var
- import_playbook: tomcat-start.yaml
  when: "'1' in var"
- import_playbook: tomcat-stop.yaml
  when: "'2' in var"
- import_playbook: tomcat-restart.yaml
  when: "'3' in var"
  
    

