---
- name: Execute a script from host
  hosts: "{{ Environment }}"


  tasks:


    - name: copy script from local to remote
      copy:
        src: *hidden*
        dest: *hidden*
        mode: 0755
      register: copy

    - name: Verifying file in locaion of the remote
      command: ls -lrt
      args:
        chdir: *hidden*
      register: copy

    - name: Verifying copy
      debug:
        msg: "{{ copy.stdout.split('\n') }}"

    - name: executing script in remote
      command: ./*hidden* "{{filename}}" "{{date}}" "{{queue}}"
      args:
        chdir: /tmp/test
      register: result


    - name: Verifying result
      debug:
        msg: "{{ result.stdout.split('\n') }}"

    - name: Write results to logfile
      blockinfile:
        create: yes
        path: "*hidden*"
        mode: 0777
        backup: yes
        insertafter: BOF
        block: "{{ result.stdout }}"
        marker: "# {{ inventory_hostname }} {mark}"
      delegate_to: localhost
      
      #paths and name of thet scripts are *hidden* due to security reasons
