- name : tomcat start
  hosts: test_servers
  tasks:
    
    - name: count the number of process
      become: yes
      become_user: res2
      shell: cat process-lst | grep tomcat | grep -v grep | wc -l
      args:
        chdir: /home/res2
      register: result

    - name: Enable tomcat
      become: yes
      become_user: res2
      command: nohup sh startup.sh &
      args:
        chdir: /opt/int1/apache-tomcat-8.5.41/bin
      when: result != 0
      register: tomstart


    - name : Verifying tomcat start
      debug:
         var: tomstart
